Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 35